main: mainPackage.main
name: DangerousCaves
version: 1.0
author: DaddyLootly
description: Adds and improves mechanics in caves.

commands:
  getworldname:
    description: Gets the name of the world you are in for use in config.
    usage: /getworldname
    permission: dangerc.getworldname
    permission-message: You don't have the dangerc.getworldname permission.